server:
  port: 8082

logging:
  file:
    path: logs

cors:
  allowed-origins: http://localhost:*

spring:
  application:
    name: knowledge-game-app
  jackson:
    serialization:
      write-dates-as-timestamps: true
  config:
    import:
      - nacos:common.yml?refresh=true
      - nacos:knowledge-game-app.yml?refresh=true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: ${NACOS_NAMESPACE:}
      config:
        namespace: ${NACOS_NAMESPACE:}

m2m:
  auth:
    enabled: true
    service-name: knowledge-game-app
    services:
      knowledge-game-file: bde80eb7-e90c-4192-a5fd-ecbcfece488e

knowledgegame:
  file:
    upload-base-url: http://localhost:8083
